define((
{
    colNameEntityName: '名稱',
    colNameType: '類型',
    colNameTable: '表格',
    colNameCreateUser: '建立使用者',
    colNameCreateDate: '建立日期',
    colNameLastExecutionDate: '上次執行',
    colNameLastExecutionUser: '上次執行者',
    colNameModifyUser: '修改使用者',
    colNameModifyDate: '修改日期',
    colNameEntityDisplayName: '顯示名稱',
    colNameEntityTableName: '表格',
    colNamePropertyCount: '內容計數',
    colNameFilterCount: '篩選計數',
    colNameMetricCount: '計量計數',
    colNamePackage: '套件',
    filterName: '名稱',
    filterDisplayName: '顯示名稱',
    filterEntityName: '實體名稱',
    filterModifiedDate: '修改日期',
    filterHasMeasure: '有測量',
    filterHasMetric: '有計量',
    filterHasFilter: '有篩選',
    filteroptionToday: '今天',
    filteroptionThisWeek: '本週',
    filteroptionThisMonth: '本月',
    filteroptionThisQuarter: '本季',
    filteroptionThisYear: '今年',
    filteroptionLastWeek: '上週',
    filteroptionLastMonth: '上個月',
    filteroptionLastQuarter: '上一季',
    filteroptionLastYear: '去年',
    filteroptionOlder: '較舊的',
    lblFilterManager: '篩選管理者',
    lblEntityManager: '實體管理者',
    FilterManager: '篩選管理者',
    EntityManager: '實體管理者',
    lblEntity: '實體',
    lblEntities: '實體',
    owner: '擁有者',
    assignTo: '指派至',
    newACI: '新區域/類別/問題...',
    insertACI: '插入新區域/類別/問題',
    autoAssign: '自動指派',
    areaCatIssue: '區域/類別/問題',
    lookupACI: '查閱區域/類別/問題',
    displayName: '顯示名稱',
    displayPluralName: 'Display Plural Name',
    Title: '標題',
    IsExtension: 'IsExtension',
    Audited: '已稽核',
    OK: '確定',
    Cancel: '取消'
}
));