define({
    lblNewEntityWizard: 'Assistant Nouvelle entité',
    lblCreateEntity: 'Create Entity',
    lblCreateEntityFromTable: 'Create a new entity from a table',
    lblEntityName: 'Nom',
    lblDisplayName: 'Affichage',
    lblPackage: 'Progiciel',
    lblEntityUsed: 'Entity Name is already used !',
    lblNext: 'Suivant',
    lblCancel: 'Annuler',
    lblBack: 'Précédent',
    lblEnterProperties: 'Enter Fields',
    lblAddNewProperty: 'Click the add(+) button to add new fields to the entity',
    lblPropertyName: 'Nom du champ',
    lblDataType: 'Type de données',
    lblLength: 'Longueur',
    lblSure: 'Are you sure ?',
    lblThisStepCreateEntity: 'L\'exécution de cette étape permet de créer des entités et le schéma nécessaire',
    lblEntity: 'Entité',
    lblProperties: 'Champs',
    lblStatus: 'Etat',
    lblSuccess: 'Opération réussie',
    lblSuccessMsg: 'Success, Entity created Successfully.',
    lblError: 'Erreur',
    lblFailed: 'Failed',
    lblErrorMsg: 'Error, Entity creation failed !',
    lblFinish: 'Terminer',
    lblInvalidEntry: 'A valid entry starts with capital letter',
    lblRequired: 'Obligatoire',
    lblErrorRelation: 'Error while creating relationship with',
    lblRelationship: 'Relation principale',
    lblSelectEntity: 'Choose whether this entity has a primary relationship to another entity',
    lblExistingEntity: 'Lier à une entité existante',
    lblRelatedEntity: 'Related Entity',
    lblRelationType: 'Relation Type',
    addFieldDialogTitle: 'Ajouter un champ',
    editFieldDialogTitle: 'Modifier le champ',
    noDeleteSysProps: 'Can not delete the system properties',
    noEditSysProps: 'Can not edit the system properties',
    NoRecordsSelected: 'Aucun enregistrement n\'est sélectionné.',
    lblNullable: 'Est nullable',
    CreateUser: 'Créé par',
    CreateDate: 'Date de création',
    ModifyUser: 'Modifié par',
    ModifyDate: 'Date de modification'
});