define("Sage/UI/Controls/nls/it/FieldAttributeControlFactory", {
    IsEncrypted: 'Viene crittografato',
    Length: 'Lunghezza',
    Precision: 'Precisione',
    Scale: 'Scala',
    LookupEntityName: 'Nome Entità Ricerca',
    LookupGroup: 'Ricerca Gruppo',
    IsPercentage: 'È la percentuale',
    Items: 'Voci',
    MultiSelect: 'Multiselect',
    OverriddenName: 'Nome Sovrascritto',
    Storage: 'Archiviazione',
    EnableHyperLinking: 'Attiva collegamento ipertestuale',
    LookupPreFilters: 'Ricerca Pre Filtri',
    EqualTo: 'Uguale a',
    NotEqualTo: 'Diverso da',
    GreaterThanOrEqual: 'Maggiore di o Uguale',
    GreaterThan: 'MaggioreDi',
    LessThanOrEqual: 'Inferiore a o Uguale',
    LessThan: 'MinoreDi',
    CondOperator: 'Operatore Condizionale',
    FilterValue: 'Valore Filtro',
    PropertyName: 'Nome Proprietà',
    LookupProperties: 'Ricerca Proprietà',
    ExcludeFromFilters: 'Escludi dai filtri',
    HideCondition: 'Nascondi Condizione',
    IsSortable: 'È ordinabile',
    PropertyFormat: 'Formato proprietà',
    None: 'Nessuno',
    Phone: 'Telefono',
    User: 'Utente',
    PickList: 'Elenco di Selezione',
    DateTime: 'Data Ora',
    PropertyFormatString: 'Stringa formato proprietà',
    PropertyHeader: 'Intestazione proprietà',
    PropertyType: 'Tipo proprietà',
    UseAsResult: 'Usa come risultato',
    ReturnPrimaryKey: 'Ritorna la chiave primaria',
    AllowMultiples: 'Consenti Multipli',
    AlphaSort: 'In ordine alfabetico',
    MustExistInList: 'Deve esistere nell\'elenco',
    NoneEditable: 'Niente Modificabile',
    PickListFilter: 'Filtro elenco di prelievo',
    ValueStoredAsText: 'Valore Archiviato Come Testo',
    Value: 'Valore',
    Display: 'Visualizza',
    Code: 'Codice',
    Name: 'Nome',
    DisplayName: 'Visualizza Nome',
    Template: 'Calcolo',
    Description: 'Descrizione',
    SortOrder: 'Criterio di ordinamento',
    lblNoFieldsInTemplate: 'Please add an entity property to the template before applying a sort order.',
    AddField: 'Aggiungi campo',
    InUse: 'In uso',
    NotInUse: 'Not In Use',
    CalculatedNumberInputError: "<p>Inputs are limited to Field Names selected via the drop down,<br/> and the following characters:<br/>&nbsp;&nbsp;&nbsp;&nbsp;'+','-','*','/','(', or ')',<br/>&nbsp;&nbsp;&nbsp;&nbsp;these match up with the button values above the text area.</p>",
    newPickList: 'Nuovo Elenco di Selezione',
    add: 'Aggiungi',
    substract: 'substract',
    multiply: 'multiply',
    divide: 'divide',
    openParens: 'open parenthesis',
    closeParens: 'close parenthesis'
});
