define({
    addText: '添加',
    deleteText: '删除',
    saveText: '保存',
    cancelText: '取消',
    editText: '编辑',
    helpText: '帮助',
    yesText: '是',
    noText: '否',
    okText: '确定',
    newPickList: '新建下拉列表',
    items: '下拉列表项目',
    number: '顺序',
    enterValue: 'Enter Value',
    lblMore: 'More',
    picklistAlreadyExists: "Picklist '${0}' already exists.",
    messageOnSave: 'Pick list, ${0}, has been saved. Please continue adding or editing the field information.',
    permissionsToView: 'You do not have permitions to view.',
    required: '必需条目',
    allowMultiples: '允许多选',
    valueMustExist: '文本必须与列表项目匹配',
    alphaSorted: '按字母顺序排序',
    noneEditable: '用户不能编辑项目'
});