define({
    addText: 'Ajouter',
    deleteText: 'Outil de suppression',
    saveText: 'Enregistrer',
    cancelText: 'Annuler',
    editText: 'Modifier',
    helpText: 'Aide',
    yesText: 'Oui',
    noText: 'Non',
    okText: 'OK',
    newPickList: 'Nouvelle liste de sélection',
    items: 'Eléments de liste de sélection',
    number: 'Commande',
    enterValue: 'Enter Value',
    lblMore: 'More',
    picklistAlreadyExists: "Picklist '${0}' already exists.",
    messageOnSave: 'Pick list, ${0}, has been saved. Please continue adding or editing the field information.',
    permissionsToView: 'You do not have permitions to view.',
    required: 'Entrée obligatoire',
    allowMultiples: 'Autoriser les sélections multiples',
    valueMustExist: 'Le texte doit correspondre à un élément de la liste',
    alphaSorted: 'Trié par ordre alphabétique',
    noneEditable: 'Les utilisateurs ne peuvent pas modifier les éléments'
});