define("Sage/UI/nls/de/BulkUpdateWidget", {
    dlgBulkActionUpdate_Title: 'Sammelaktionsaktualisierung',
    pageLoading_Caption: 'Eigenschaftsoptionen werden geladen...',
    header_Caption: 'Wählen Sie eine Eigenschaft aus, die aktualisiert werden soll.',
    header_NoPropertiesEnabled: 'The ${0} entity is enabled for bulk updates, however, there are no properties that have been enabled. Please contact your system administrator for more information',
    errorRequestPropertyOptions: 'Fehler beim Lesen von Metadaten für die Entität ${0}. ${1}',
    errorEntityNotSupported: "Entität ${0} unterstützt keine Sammelaktualisierungen",
    update_Property_Caption: 'Aktualisieren:',
    addProperty_Tooltip: 'Eigenschaft hinzufügen',
    removeProperty_Tooltip: 'Eigenschaft entfernen',
    no_Caption: 'Nein',
    yes_Caption: 'Ja',
    days_Caption: 'Tage',
    moveOut_Caption: 'Verschieben',
    moveTo_Caption: 'An',
    moveDate_Backward: 'Zurück',
    moveDate_Forward: 'Vorwärts',
    update_To_Caption: 'Bis:',
    lookupHeaderText: 'Suche ${0}',
    lookupNameColText: 'Name',
    lookupTitleColText: 'Titel',
    lookupDepartmentColText: 'Abteilung',
    lookupRegionColText: 'Region',
    lookupTypeColText: 'Typ',
    lookupDescriptionColText: 'Beschreibung',
    btnOK_Caption: 'OK',
    btnCancel_Caption: 'Abbrechen',
    errorUnspecifiedValue: 'Geben Sie einen Wert ein, bevor Sie den Vorgang fortsetzen, oder entfernen Sie die ungültige Zeile.',
    errorRequestingJobMgr: 'Bei der Aktualisierung ist ein Fehler aufgetreten: ${0}',
    selectOption_Caption: 'Wählen Sie eine Option aus...',
    updateRecords_Caption: 'Ausgewählte Datensätze werden aktualisiert',
    chkScheduleJob_Caption: 'Planen Sie diese Aktualisierung für ein bestimmtes Datum und eine bestimmte Uhrzeit ein.',
    lookup_Caption: 'Suchen',
    job_Description: 'Fehler bei Sammelaktionsaktualisierung',
    errorDuplicateValue: 'Die Eigenschaft wurde bereits ausgewählt',
    errorInvalidPropertyType: 'Der Eigenschaftstyp \'${0}\' wird für Sammelaktionsaktualisierungen nicht unterstützt.',
    calculatedField: 'Berechnetes Feld',
    standardId: 'Standard-ID',
    unknownPropertyType: 'Unbekannt'
});