define((
{ titleFmtString: '${0}',
  tabDisplayNameActivity: '活動',
  tabDisplayNameLit: '文宣',
  tabDisplayNameEvent: '事件',
  tabDisplayNameConfirm: '確認',
  activityColNameComplete: '完成',
  activityColNameAttachment: '附件',
  activityColNameRecurring: '週期性',
  activityColNameAlarm: '鬧鐘',
  activityColNameType: '活動類型',
  activityColNameStartDate: '開始日期',
  activityColNameDuration: '持續時間',
  activityColNameContact: '聯絡人',
  activityColNameLead: '銷售線索',
  activityColNameAccount: '客戶',
  activityColNameRegarding: '關於',
  activityColNamePriority: '優先順序',
  activityColNameUserId: '負責人',
  activityTypePhone: '電話',
  activityTypeCall: '撥打',
  activityTypeMeeting: '會議',
  activityTypePersonal: '個人' }
));