define({
    lblNewEntityWizard: 'Новый  мастер создания сущности',
    lblCreateEntity: 'Create Entity',
    lblCreateEntityFromTable: 'Create a new entity from a table',
    lblEntityName: 'Имя',
    lblDisplayName: 'Отображение',
    lblPackage: 'Пакет',
    lblEntityUsed: 'Entity Name is already used !',
    lblNext: 'Следующий',
    lblCancel: 'Отмена',
    lblBack: 'Назад',
    lblEnterProperties: 'Enter Fields',
    lblAddNewProperty: 'Click the add(+) button to add new fields to the entity',
    lblPropertyName: 'Название поля',
    lblDataType: 'Тип данных',
    lblLength: 'Длина',
    lblSure: 'Are you sure ?',
    lblThisStepCreateEntity: 'Завершение этого шага создаст сущность и необходимую схему.',
    lblEntity: 'Сущность',
    lblProperties: 'Поля',
    lblStatus: 'Статус',
    lblSuccess: 'Успешно',
    lblSuccessMsg: 'Success, Entity created Successfully.',
    lblError: 'Ошибка',
    lblFailed: 'Failed',
    lblErrorMsg: 'Error, Entity creation failed !',
    lblFinish: 'Завершить',
    lblInvalidEntry: 'A valid entry starts with capital letter',
    lblRequired: 'Требуется',
    lblErrorRelation: 'Error while creating relationship with',
    lblRelationship: 'Первичное отношение',
    lblSelectEntity: 'Choose whether this entity has a primary relationship to another entity',
    lblExistingEntity: 'Отношение к существующей сущности',
    lblRelatedEntity: 'Related Entity',
    lblRelationType: 'Relation Type',
    addFieldDialogTitle: 'Добавить поле',
    editFieldDialogTitle: 'Редактировать поле',
    noDeleteSysProps: 'Can not delete the system properties',
    noEditSysProps: 'Can not edit the system properties',
    NoRecordsSelected: 'Нет выбранных записей.',
    lblNullable: 'Допускает значение NULL',
    CreateUser: 'Создано',
    CreateDate: 'Дата создания',
    ModifyUser: 'Кто обновил',
    ModifyDate: 'Дата обновления'
});