define({
    addText: 'Добавить',
    deleteText: 'Удалить',
    saveText: 'Сохранить',
    cancelText: 'Отмена',
    editText: 'Изменить',
    helpText: 'Помощь',
    yesText: 'Да',
    noText: 'Нет',
    okText: 'ОК',
    newPickList: 'Новый справочник',
    items: 'Знач. справочника',
    number: '№',
    enterValue: 'Enter Value',
    lblMore: 'More',
    picklistAlreadyExists: "Picklist '${0}' already exists.",
    messageOnSave: 'Pick list, ${0}, has been saved. Please continue adding or editing the field information.',
    permissionsToView: 'You do not have permitions to view.',
    required: 'Требуется вход',
    allowMultiples: 'Разрешить множественный выбор',
    valueMustExist: 'Текст должен совпадать с элементом списка',
    alphaSorted: 'Отсортировано по алфавиту',
    noneEditable: 'Пользователи не могут изменять элементы'
});