define((
{ titleFmtString: '${0}',
  tabDisplayNameActivity: '活动',
  tabDisplayNameLit: '营销材料',
  tabDisplayNameEvent: '事件',
  tabDisplayNameConfirm: '确认',
  activityColNameComplete: '完成',
  activityColNameAttachment: '附件',
  activityColNameRecurring: '定期',
  activityColNameAlarm: '警报',
  activityColNameType: 'ActivityType',
  activityColNameStartDate: '开始日期',
  activityColNameDuration: '持续时间',
  activityColNameContact: '联系人',
  activityColNameLead: '销售线索',
  activityColNameAccount: '客户',
  activityColNameRegarding: '事项',
  activityColNamePriority: '优先级',
  activityColNameUserId: '负责人',
  activityTypePhone: '电话',
  activityTypeCall: '呼叫',
  activityTypeMeeting: '会议',
  activityTypePersonal: '私人电话' }
));