define("Sage/MainView/EntityMgr/AddEditEntityDetail/nls/it/AddEditDialog", {
        // Add/Edit labels
        lblFilter: "Filtro",
        lblMetric: "Metrica",
        lblFilters: "Filtri",
        lblMetrics: "Metriche",
        lblDistinct: "Singolo",
        lblRange: "Intervallo",
        lblUserLookup: "Ricerca Utente",
        lblAdd: "Aggiungi",
        lblEdit: "Modifica",
        lblRemove: "Rimuovi",
        lblHelp: 'Aiuto',
        lblFilterName: "Nome Filtro",
        lblMetricName: "Nome metrica",
        lblDisplayName: "Visualizza Nome",
        lblName: "Nome",
        lblDisplay: "Visualizza",
        lblCalculated: "Calcolato",
        lblCalculation: "Calcolo",
        lblDescription: "Descrizione",
        lblFieldsName: "Nome campo",
        lblCalculatedFieldsName: "Nome campo calcolato",
        lblFilterDp: "Fields",
        lblTypeDp: "Tipo",
        lblCharacter: "Carattere",
        lblFrom: "Da",
        lblTo: "A",
        lblOperators: "Operatori",
        lblAggregation: "Aggregazioni",
        lblTypeSpecificContentBox: "Casella contenuto di tipo specifico",
        lblSaveButton: "OK",
        lblCancelButton: "Annulla",
        DateDiffCheckerValue: "Data metrica differente",
        InvalidFilterName: "Nome Filtro Non valido",
        InvalidRangeName: "Nome metrica non valido",
        RequiredFilterName: "Nome filtro obbligatorio",
        RequiredRangeName: "Nome intervallo obbligatorio",
        FieldMustBeANumber: "Il campo Carattere deve essere un numero intero",
        SelectAnItem: "Selezionare un elemento",
        ItemRequired: "Elemento obbligatorio",
        ItemInvalid: "Elemento non valido",
        LowerMustBeLessThanUpper: "Il valore inferiore deve essere più piccolo del valore superiore.",
        defaultRangeRowValue: "Immettere un valore",
        totalRecordCountLabel: "Totale record: ${0}",
        lblNew: "Nuovo",
        lblExisting: "Esistente",
        lblExistingCalc: "Campo calcolato esistente",
        validNameMsg: "Una voce valida inizia con una lettera maiuscola e<br> può contenere valori alfanumerici e caratteri di sottolineatura.",
      
    propertyName: 'Nome',
    displayName: 'Visualizza',
    dataTypeId: 'Tipo',
    dataTypeData: 'Attributi di tipo',
    length: 'Lunghezza',
    scale: 'Scala',
    precision: 'Precisione',
    isIncluded: 'Incluso',
    isReadOnly: 'Sola Lettura',
    displayCategory: 'Categoria Visualizzazione',
    sdata: 'Sdata',
    bulkAction: 'Azione di massa',
    canBulkUpdate: 'Può effettuare aggiornamenti di massa',
    canImport: 'Importa',
    canMatch: 'Accoppia',
    generate: 'Creare',
    audited: 'Esaminato',
    //errors
    notUniqueFor: 'non è unico per',
    notUnique: 'is not unique',
    nlsCode: 'NLS Code',
    nlsName: 'NLS Name',
    showTranslations: 'Show translations',
    hideTranslations: 'Hide translations',
    standardIds: 'Standard Ids',
    others: 'Others',
    SelectField: 'Please select a field !',
    SelectOneField: 'Please select only one field !',
    parent: 'Parent Entity and Join Field',
    child: 'Child Entity and Join Field',
    cardinality: 'Relazione',
    cascade: 'Sovrapposte',
    includeParent: 'Include parent relationship property in the child entity',
    includeChild: 'Include child relationship property in the parent entity',
    existingRelaton: 'This relationship already exists !'
   
});