define("Sage/UI/nls/ru/BulkUpdateWidget", {
    dlgBulkActionUpdate_Title: 'Массовое действие - обновление',
    pageLoading_Caption: 'Загрузка параметров свойства...',
    header_Caption: 'Выберите свойство для обновления.',
    header_NoPropertiesEnabled: 'The ${0} entity is enabled for bulk updates, however, there are no properties that have been enabled. Please contact your system administrator for more information',
    errorRequestPropertyOptions: 'Ошибка чтения метаданных для объекта ${0}. ${1}',
    errorEntityNotSupported: "Объект ${0} не поддерживает масс-обновления",
    update_Property_Caption: 'Обновление:',
    addProperty_Tooltip: 'Добавить свойство',
    removeProperty_Tooltip: 'Удалить свойство',
    no_Caption: 'Нет',
    yes_Caption: 'Да',
    days_Caption: 'Дней',
    moveOut_Caption: 'Переместить',
    moveTo_Caption: 'Кому',
    moveDate_Backward: 'Назад',
    moveDate_Forward: 'Вперед',
    update_To_Caption: 'Кому:',
    lookupHeaderText: 'Код поиска ${0}',
    lookupNameColText: 'Имя',
    lookupTitleColText: 'Название',
    lookupDepartmentColText: 'Отдел',
    lookupRegionColText: 'Регион',
    lookupTypeColText: 'Тип',
    lookupDescriptionColText: 'Описание',
    btnOK_Caption: 'ОК',
    btnCancel_Caption: 'Отмена',
    errorUnspecifiedValue: 'Перед продолжением введите значение либо удалите недопустимую строку.',
    errorRequestingJobMgr: 'Ошибка при выполнении обновления: ${0}',
    selectOption_Caption: 'Выберите параметры...',
    updateRecords_Caption: 'Обновление выбранных записей',
    chkScheduleJob_Caption: 'Запланируйте обновление на конкретное время и дату.',
    lookup_Caption: 'Поиск',
    job_Description: 'Ошибки масс-обновления',
    errorDuplicateValue: 'Свойство уже выбрано',
    errorInvalidPropertyType: 'Тип свойства \'${0}\' не поддерживается для масс-обновлений.',
    calculatedField: 'Вычисляемое поле',
    standardId: 'Стандартный ИД',
    unknownPropertyType: 'Неизвестен'
});