import declare from 'dojo/_base/declare';
import Base from './Base';
import _SDataModelBase from 'argos/Models/_SDataModelBase';
import Manager from 'argos/Models/Manager';
import MODEL_TYPES from 'argos/Models/Types';
import MODEL_NAMES from '../Names';

const __class = declare('icboe.Models.SalesOrderItem.SData', [Base, _SDataModelBase], {
  id: 'salesorderitem_sdata_model',
  createQueryModels: function createQueryModels() {
    return [{
      name: 'list',
      queryOrderBy: 'ErpLineNumber',
      querySelect: [
        'Description',
        'ErpLineNumber',
        'ExtendedPrice',
        'ErpStatus',
        'ErpStatusDate',
        'Quantity',
        'Price',
        'ExtendedPrice',
        'DocExtendedPrice',
        'CalculatedPrice',
        'DocCalculatedPrice',
        'ProductName',
        'CreateDate',
        'ModifyDate',
        'SlxLocation/Description',
        'SalesOrder/ErpLogicalId',
        'SalesOrder/SalesOrderNumber',
        'Salesorder/CurrencyCode',
      ],
    }, {
      name: 'detail',
      querySelect: [
        'Description',
        'ErpLineNumber',
        'ActualID',
        'Discount',
        'ExtendedPrice',
        'DocExtendedPrice',
        'CalculatedPrice',
        'DocCalculatedPrice',
        'ErpStatus',
        'Quantity',
        'Price',
        'ProductName',
        'CreateDate',
        'ModifyDate',
        'SalesOrder/SalesOrderNumber',
        'SalesOrder/CurrencyCode',
        'ErpShippedQuantity',
        'ErpOpenQuantity',
        'ErpDropShip',
        'ErpBackOrdered',
        'ErpPartialShipAllowed',
        'ErpFixedPriceItem',
        'ErpRushRequest',
        'ErpSubstituteItem',
        'SalesOrder/ErpLocation',
        'Product/*',
        'SlxLocation/*',
        'UnitOfMeasure/*',
      ],
    }, {
      name: 'edit',
      querySelect: [
        'Description',
        'ErpLineTotalAmount',
        'ActualID',
        'Discount',
        'ErpStatus',
        'Quantity',
        'Price',
        'ExtendedPrice',
        'DocExtendedPrice',
        'CalculatedPrice',
        'DocCalculatedPrice',
        'ErpUnitPrice',
        'ProductName',
        'CreateDate',
        'ModifyDate',
        'SalesOrder/SalesOrderNumber',
        'SalesOrder/CurrencyCode',
        'ErpShippedQuantity',
        'ErpOpenQuantity',
        'ErpDropShip',
        'ErpBackOrdered',
        'ErpPartialShipAllowed',
        'ErpFixedPriceItem',
        'ErpRushRequest',
        'ErpSubstituteItem',
        'SalesOrder/ErpLocation',
        'Product/*',
        'SlxLocation/*',
        'UnitOfMeasure/*',
      ],
    },
  ];
  },
});

Manager.register(MODEL_NAMES.SALESORDERITEM, MODEL_TYPES.SDATA, __class);
export default __class;
