define({
    addText: '新增',
    deleteText: '刪除',
    saveText: '儲存',
    cancelText: '取消',
    editText: '編輯',
    helpText: '說明',
    yesText: '是',
    noText: '否',
    okText: '確定',
    newPickList: '新增挑選清單',
    items: '挑選清單項目',
    number: '順序',
    enterValue: 'Enter Value',
    lblMore: 'More',
    picklistAlreadyExists: "Picklist '${0}' already exists.",
    messageOnSave: 'Pick list, ${0}, has been saved. Please continue adding or editing the field information.',
    permissionsToView: 'You do not have permitions to view.',
    required: '必要項目',
    allowMultiples: '允許多個選取項目',
    valueMustExist: '文字必須與清單項目相符',
    alphaSorted: '依照英文字母順序排序',
    noneEditable: '使用者無法編輯項目'
});