define({
    lblNewEntityWizard: 'Assistent für neue Entitäten',
    lblCreateEntity: 'Create Entity',
    lblCreateEntityFromTable: 'Create a new entity from a table',
    lblEntityName: 'Name',
    lblDisplayName: 'Anzeigen',
    lblPackage: 'Paket',
    lblEntityUsed: 'Entity Name is already used !',
    lblNext: 'Weiter',
    lblCancel: 'Abbrechen',
    lblBack: 'Zurück',
    lblEnterProperties: 'Enter Fields',
    lblAddNewProperty: 'Click the add(+) button to add new fields to the entity',
    lblPropertyName: 'Feldname',
    lblDataType: 'Datentyp',
    lblLength: 'Länge',
    lblSure: 'Are you sure ?',
    lblThisStepCreateEntity: 'Mit der Durchführung dieses Schrittes erstellen Sie die Entitäten und das notwendige Schema.',
    lblEntity: 'Entität',
    lblProperties: 'Felder',
    lblStatus: 'Status',
    lblSuccess: 'Erfolg',
    lblSuccessMsg: 'Success, Entity created Successfully.',
    lblError: 'Fehler',
    lblFailed: 'Failed',
    lblErrorMsg: 'Error, Entity creation failed !',
    lblFinish: 'Fertig stellen',
    lblInvalidEntry: 'A valid entry starts with capital letter',
    lblRequired: 'Erforderlich',
    lblErrorRelation: 'Error while creating relationship with',
    lblRelationship: 'Primäre Beziehung',
    lblSelectEntity: 'Choose whether this entity has a primary relationship to another entity',
    lblExistingEntity: 'In Beziehung zu vorhandener Entität setzen',
    lblRelatedEntity: 'Related Entity',
    lblRelationType: 'Relation Type',
    addFieldDialogTitle: 'Feld hinzufügen',
    editFieldDialogTitle: 'Feld bearbeiten',
    noDeleteSysProps: 'Can not delete the system properties',
    noEditSysProps: 'Can not edit the system properties',
    NoRecordsSelected: 'Es sind keine Datensätze ausgewählt.',
    lblNullable: 'Darf Null sein',
    CreateUser: 'Angelegt von',
    CreateDate: 'Erstellungsdatum',
    ModifyUser: 'Geändert von',
    ModifyDate: 'Datum ändern'
});