define("Sage/UI/Controls/nls/ru/FieldAttributeControlFactory", {
    IsEncrypted: 'Зашифрован',
    Length: 'Длина',
    Precision: 'Точность',
    Scale: 'Шкала',
    LookupEntityName: 'Название сущности поиска',
    LookupGroup: 'Группа поиска',
    IsPercentage: 'Является процентом?',
    Items: 'Элементы',
    MultiSelect: 'Множ. выбор',
    OverriddenName: 'Отмененное имя',
    Storage: 'Память',
    EnableHyperLinking: 'Включить гиперссылки',
    LookupPreFilters: 'Предв. фильтр поиска',
    EqualTo: 'Равно',
    NotEqualTo: 'Не равно',
    GreaterThanOrEqual: 'Больше чем или равно',
    GreaterThan: 'Больше чем',
    LessThanOrEqual: 'Меньше чем или равно',
    LessThan: 'Меньше чем',
    CondOperator: 'Оператор условия',
    FilterValue: 'Значение фильтра',
    PropertyName: 'Название свойства',
    LookupProperties: 'Свойства поиска',
    ExcludeFromFilters: 'Исключить из фильтров',
    HideCondition: 'Условие скрытия',
    IsSortable: 'Возможна сортировка',
    PropertyFormat: 'Формат свойства',
    None: 'Нет',
    Phone: 'Телефон',
    User: 'Пользователь',
    PickList: 'Справочник',
    DateTime: 'Дата и время',
    PropertyFormatString: 'Строка формата свойства',
    PropertyHeader: 'Заголовок свойства',
    PropertyType: 'Тип свойства',
    UseAsResult: 'Использовать как результат',
    ReturnPrimaryKey: 'Возврат первичного ключа',
    AllowMultiples: 'Разрешить множественность',
    AlphaSort: 'Буквенн. сортировка',
    MustExistInList: 'Множ. выбор',
    NoneEditable: 'Не редактируемо',
    PickListFilter: 'Фильтр списка выбора',
    ValueStoredAsText: 'Значение сохранено как текст',
    Value: 'Значение',
    Display: 'Отображение',
    Code: 'Код',
    Name: 'Имя',
    DisplayName: 'Название',
    Template: 'Вычисление',
    Description: 'Описание',
    SortOrder: 'Порядок сортировки',
    lblNoFieldsInTemplate: 'Please add an entity property to the template before applying a sort order.',
    AddField: 'Добавить поле',
    InUse: 'Используется',
    NotInUse: 'Not In Use',
    CalculatedNumberInputError: "<p>Inputs are limited to Field Names selected via the drop down,<br/> and the following characters:<br/>&nbsp;&nbsp;&nbsp;&nbsp;'+','-','*','/','(', or ')',<br/>&nbsp;&nbsp;&nbsp;&nbsp;these match up with the button values above the text area.</p>",
    newPickList: 'Новый справочник',
    add: 'Добавить',
    substract: 'substract',
    multiply: 'multiply',
    divide: 'divide',
    openParens: 'open parenthesis',
    closeParens: 'close parenthesis'
});
