define({
    lblNewEntityWizard: 'New Entity Wizard',
    lblCreateEntity: 'Create Entity',
    lblCreateEntityFromTable: 'Create a new entity from a table',
    lblEntityName: 'Nome',
    lblDisplayName: 'Visualizza',
    lblPackage: 'Pacchetto',
    lblEntityUsed: 'Entity Name is already used !',
    lblNext: 'Avanti',
    lblCancel: 'Annulla',
    lblBack: 'Indietro',
    lblEnterProperties: 'Enter Fields',
    lblAddNewProperty: 'Click the add(+) button to add new fields to the entity',
    lblPropertyName: 'Nome campo',
    lblDataType: 'Tipo Dati',
    lblLength: 'Lunghezza',
    lblSure: 'Are you sure ?',
    lblThisStepCreateEntity: 'Completing this step will create the entities and necessary schema',
    lblEntity: 'Entità',
    lblProperties: 'Fields',
    lblStatus: 'Status',
    lblSuccess: 'Completato',
    lblSuccessMsg: 'Success, Entity created Successfully.',
    lblError: 'Errore',
    lblFailed: 'Failed',
    lblErrorMsg: 'Error, Entity creation failed !',
    lblFinish: 'Fine',
    lblInvalidEntry: 'A valid entry starts with capital letter',
    lblRequired: 'Obbligatorio',
    lblErrorRelation: 'Error while creating relationship with',
    lblRelationship: 'Primary Relationship',
    lblSelectEntity: 'Choose whether this entity has a primary relationship to another entity',
    lblExistingEntity: 'Relate to an existing entity',
    lblRelatedEntity: 'Related Entity',
    lblRelationType: 'Relation Type',
    addFieldDialogTitle: 'Aggiungi campo',
    editFieldDialogTitle: 'Modifica campo',
    noDeleteSysProps: 'Can not delete the system properties',
    noEditSysProps: 'Can not edit the system properties',
    NoRecordsSelected: 'Non ci sono record selezionati.',
    lblNullable: 'Annullabile',
    CreateUser: 'Creato da',
    CreateDate: 'Data Creazione',
    ModifyUser: 'Utente Modifica',
    ModifyDate: 'Data Modifica'
});