define("Sage/MainView/EntityMgr/AddEditEntityDetail/nls/fr/AddEditDialog", {
        // Add/Edit labels
        lblFilter: "Filtrer",
        lblMetric: "Mesure",
        lblFilters: "Filtres",
        lblMetrics: "Mesures",
        lblDistinct: "Distinct",
        lblRange: "Plage",
        lblUserLookup: "Rechercher un utilisateur",
        lblAdd: "Ajouter",
        lblEdit: "Modifier",
        lblRemove: "Retirer",
        lblHelp: 'Aide',
        lblFilterName: "Nom du filtre",
        lblMetricName: "Nom de la mesure",
        lblDisplayName: "Nom d'affichage",
        lblName: "Nom",
        lblDisplay: "Affichage",
        lblCalculated: "Calculé(e)(s)",
        lblCalculation: "Calcul",
        lblDescription: "Description",
        lblFieldsName: "Nom des champs",
        lblCalculatedFieldsName: "Nom des champs calculés",
        lblFilterDp: "Champs",
        lblTypeDp: "Type",
        lblCharacter: "Caractère",
        lblFrom: "De",
        lblTo: "À",
        lblOperators: "Opérateurs",
        lblAggregation: "Agrégations",
        lblTypeSpecificContentBox: "Zone de contenu spécifique de type",
        lblSaveButton: "OK",
        lblCancelButton: "Annuler",
        DateDiffCheckerValue: "Mesure de différence de date",
        InvalidFilterName: "Nom de filtre non valide",
        InvalidRangeName: "Nom de plage incorrect",
        RequiredFilterName: "Nom de filtre obligatoire",
        RequiredRangeName: "Nom de plage obligatoire",
        FieldMustBeANumber: "Le champ Caractère doit être un nombre entier.",
        SelectAnItem: "Sélectionnez un élément",
        ItemRequired: "Elément obligatoire",
        ItemInvalid: "Elément incorrect",
        LowerMustBeLessThanUpper: "La valeur la plus basse doit être inférieure à la valeur la plus haute.",
        defaultRangeRowValue: "Saisir une valeur",
        totalRecordCountLabel: "Nombre total d'enregistrements : ${0}",
        lblNew: "Nouveau",
        lblExisting: "Existant",
        lblExistingCalc: "Champ calculé existant",
        validNameMsg: "Pour être valide, l'entrée doit commencer par une lettre majuscule. Elle <br> peut contenir des valeurs alphanumériques et des traits de soulignement.",
      
    propertyName: 'Nom',
    displayName: 'Affichage',
    dataTypeId: 'Type',
    dataTypeData: 'Attributs du type',
    length: 'Longueur',
    scale: 'Echelle',
    precision: 'Précision',
    isIncluded: 'Inclus',
    isReadOnly: 'Lecture seule',
    displayCategory: 'Afficher la catégorie',
    sdata: 'SData',
    bulkAction: 'Action en bloc',
    canBulkUpdate: 'Peut effectuer une mise à jour en masse',
    canImport: 'Importer',
    canMatch: 'Faire correspondre',
    generate: 'Générer',
    audited: 'Audité',
    //errors
    notUniqueFor: 'n\'est pas unique pour',
    notUnique: 'is not unique',
    nlsCode: 'NLS Code',
    nlsName: 'NLS Name',
    showTranslations: 'Show translations',
    hideTranslations: 'Hide translations',
    standardIds: 'ID standard',
    others: 'Others',
    SelectField: 'Please select a field !',
    SelectOneField: 'Please select only one field !',
    parent: 'Parent Entity and Join Field',
    child: 'Child Entity and Join Field',
    cardinality: 'Relation',
    cascade: 'Cascade',
    includeParent: 'Include parent relationship property in the child entity',
    includeChild: 'Include child relationship property in the parent entity',
    existingRelaton: 'This relationship already exists !'
   
});