define((
{
    colNameEntityName: 'Name',
    colNameType: 'Typ',
    colNameTable: 'Tabelle',
    colNameCreateUser: 'Angelegt von',
    colNameCreateDate: 'Erstellungsdatum',
    colNameLastExecutionDate: 'Letzte Ausführung',
    colNameLastExecutionUser: 'Letzte Ausführung durch',
    colNameModifyUser: 'Geändert von',
    colNameModifyDate: 'Datum ändern',
    colNameEntityDisplayName: 'Anzeigename',
    colNameEntityTableName: 'Tabelle',
    colNamePropertyCount: 'Eigenschaftenanzahl',
    colNameFilterCount: 'Filteranzahl',
    colNameMetricCount: 'Kennzahlanzahl',
    colNamePackage: 'Paket',
    filterName: 'Name',
    filterDisplayName: 'Anzeigename',
    filterEntityName: 'Entitätsname',
    filterModifiedDate: 'Änderungsdatum',
    filterHasMeasure: 'Mit Maßeinheit',
    filterHasMetric: 'Mit Kennzahl',
    filterHasFilter: 'Mit Filter',
    filteroptionToday: 'Heute',
    filteroptionThisWeek: 'Diese Woche',
    filteroptionThisMonth: 'Diesen Monat',
    filteroptionThisQuarter: 'Dieses Quartal',
    filteroptionThisYear: 'Dieses Jahr',
    filteroptionLastWeek: 'Letzte Woche',
    filteroptionLastMonth: 'Letzter Monat',
    filteroptionLastQuarter: 'Letztes Quartal',
    filteroptionLastYear: 'Letztes Jahr',
    filteroptionOlder: 'Älter',
    lblFilterManager: 'Filter-Manager',
    lblEntityManager: 'Entitäts-Manager',
    FilterManager: 'FilterManager',
    EntityManager: 'EntitätsManager',
    lblEntity: 'Entität',
    lblEntities: 'Entitäten',
    owner: 'Zugriffsberechtigter',
    assignTo: 'Zuweisen zu',
    newACI: 'Neuer Bereich/Neue Kategorie/Neues Problem',
    insertACI: 'Bereich/Kategorie/Problem einfügen',
    autoAssign: 'Automatische Zuweisung',
    areaCatIssue: 'Bereich/Kategorie/Problem',
    lookupACI: 'Suche Bereich/Kategorie/Problem',
    displayName: 'Anzeigename',
    displayPluralName: 'Display Plural Name',
    Title: 'Titel',
    IsExtension: 'IsExtension',
    Audited: 'Geprüft',
    OK: 'OK',
    Cancel: 'Abbrechen'
}
));