define("Sage/UI/Controls/nls/de/PropertyStore", {
    // data types
    "Text": 'Text',
    memo: 'Memo',
    unicodeText: 'Unicode-Text',
    unicodeMemo: 'Unicode-Memo',
    "Ganzzahl": 'Ganzzahl',
    "Double": 'Double',
    single: 'Single',
    "Dezimal": 'Dezimal',
    "kurz": 'kurz',
    standardId: 'Standard-ID',
    trueFalse: 'Wahr/Falsch',
    yesNo: 'Ja/Nein',
    "Boolesch": 'Boolesch',
    dateTime: 'Datum/Zeit',
    email: 'E-Mail',
    phone: 'Telefon',
    pickList: 'Auswahlliste',
    owner: 'Zugriffsberechtigter',
    lookup: 'Suchen',
    dependencyLookup: 'Abhängigkeitensuche',
    "Zeichen": 'Zeichen',
    enum_: 'Enum',
    "GUID": 'GUID',
    "Byte": 'Byte',
    "Binär": 'Binär',
    "URL": 'URL',
    "Zeichenfolge": 'Zeichenfolge',
    "Zahl": 'Zahl',
    id: 'ID',
    code: 'Code',
    name: 'Name',
    value: 'Wert',
    "Systemeigen": 'Systemeigen',
    calc: 'Berechnetes Feld',
    calcSF: 'Berechnete Zeichenfolge',
    calcNF: 'Berechnete Zahl'

});
