define({
    addText: 'Aggiungi',
    deleteText: 'Elimina',
    saveText: 'Salva',
    cancelText: 'Annulla',
    editText: 'Modifica',
    helpText: 'Aiuto',
    yesText: 'Sì',
    noText: 'No',
    okText: 'OK',
    newPickList: 'Nuovo Elenco di Selezione',
    items: 'Id Voci Elenco di Selezione',
    number: 'Ordine',
    enterValue: 'Enter Value',
    lblMore: 'More',
    picklistAlreadyExists: "Picklist '${0}' already exists.",
    messageOnSave: 'Pick list, ${0}, has been saved. Please continue adding or editing the field information.',
    permissionsToView: 'You do not have permitions to view.',
    required: 'Required Entry',
    allowMultiples: 'Allow Multiple Selections',
    valueMustExist: 'Il testo deve coincidere con una voce dell\'elenco',
    alphaSorted: 'In ordine alfabetico',
    noneEditable: 'Users cannot edit items'
});