define((
{
    colNameEntityName: '名称',
    colNameType: '类型',
    colNameTable: '表格',
    colNameCreateUser: '创建用户',
    colNameCreateDate: '创建日期',
    colNameLastExecutionDate: '上次运行时间',
    colNameLastExecutionUser: '上次运行用户',
    colNameModifyUser: '修改用户',
    colNameModifyDate: '修改日期',
    colNameEntityDisplayName: '显示名称',
    colNameEntityTableName: '表格',
    colNamePropertyCount: '属性计数',
    colNameFilterCount: '筛选器计数',
    colNameMetricCount: '度量计数',
    colNamePackage: '包',
    filterName: '名称',
    filterDisplayName: '显示名称',
    filterEntityName: '实体名称',
    filterModifiedDate: '修改日期',
    filterHasMeasure: '具有度量值',
    filterHasMetric: '具有度量',
    filterHasFilter: '具有筛选器',
    filteroptionToday: '今天',
    filteroptionThisWeek: '本周',
    filteroptionThisMonth: '本月',
    filteroptionThisQuarter: '本季度',
    filteroptionThisYear: '本年',
    filteroptionLastWeek: '上一周',
    filteroptionLastMonth: '上一月',
    filteroptionLastQuarter: '上一季度',
    filteroptionLastYear: '上一年',
    filteroptionOlder: '早于',
    lblFilterManager: '筛选器管理器',
    lblEntityManager: '实体管理器',
    FilterManager: '筛选器管理器',
    EntityManager: '实体管理器',
    lblEntity: '实体',
    lblEntities: '实体',
    owner: '所有者',
    assignTo: '分配给',
    newACI: '新建所属范围/类别/问题...',
    insertACI: '插入新的所属范围/类别/问题',
    autoAssign: '自动分配',
    areaCatIssue: '所属范围/类别/问题',
    lookupACI: '查找所属范围/类别/问题',
    displayName: '显示名称',
    displayPluralName: 'Display Plural Name',
    Title: '标题',
    IsExtension: 'IsExtension',
    Audited: '已审计',
    OK: '确定',
    Cancel: '取消'
}
));