import declare from 'dojo/_base/declare';
import Base from './Base';
import _SDataModelBase from 'argos/Models/_SDataModelBase';
import Manager from 'argos/Models/Manager';
import MODEL_TYPES from 'argos/Models/Types';
import MODEL_NAMES from '../Names';

const __class = declare('icboe.Models.SalesOrder.SData', [Base, _SDataModelBase], {
  id: 'salesorder_sdata_model',
  createQueryModels: function createQueryModels() {
    return [{
      name: 'list',
      queryWhere: 'IsQuote eq false',
      queryOrderBy: 'OrderDate desc',
      querySelect: [
        'SalesOrderNumber',
        'Account/AccountName',
        'Status',
        'ErpExtId',
        'CustomerPurchaseOrderNumber',
        'GrandTotal',
        'OrderDate',
        'CreateDate',
        'ModifyDate',
        'CurrencyCode',
      ],
    }, {
      name: 'detail',
      querySelect: [
        'SalesOrderNumber',
        'ErpExtId',
        'CustomerPurchaseOrderNumber',
        'Account/AccountName',
        'Opportunity/Description',
        'Quote/QuoteNumber',
        'CreateDate',
        'ModifyDate',
        'OrderDate',
        'DueDate',
        'Status',
        'StatusDate',
        'ErpShipTo/Name',
        'ErpShipTo/Address/*',
        'ErpBillTo/Name',
        'ErpBillTo/Address/*',
        'ErpPayFrom/Address/*',
        'DocGrandTotal',
        'DocOrderTotal',
        'GrandTotal',
        'OrderTotal',
        'ErpPaymentMethod',
        'ErpPaymentTermId',
        'ErpBackOrdered',
        'ErpDropShip',
        'ErpShipEarly',
        'ErpInvoiceImmediately',
        'ErpPartialShipAllowed',
        'ErpTaxExempt',
        'CurrencyCode',
        'ErpLogicalId',
        'ErpAccountingEntityId',
        'ExchangeRate',
        'SyncStatus',
        'AccountManager/*',
        'ErpLocation',
        'WarehouseLocation/Address/*',
        'WarehouseLocation/Description',
        'Location/Address/*',
        'Location/Description',
        'RequestedBy/NameLF',
        'Carrier/CarrierName',
      ],
    }, {
      name: 'edit',
      querySelect: [
        'SalesOrderNumber',
        'ErpExtId',
        'CustomerPurchaseOrderNumber',
        'Account/AccountName',
        'Opportunity/Description',
        'Quote/QuoteNumber',
        'CreateDate',
        'ModifyDate',
        'OrderDate',
        'DueDate',
        'Status',
        'StatusDate',
        'ErpShipTo/Address/*',
        'ErpBillTo/Address/*',
        'ErpPayFrom/Address/*',
        'GrandTotal',
        'OrderTotal',
        'ErpPaymentMethod',
        'ErpPaymentTermId',
        'ErpBackOrdered',
        'ErpDropShip',
        'ErpShipEarly',
        'ErpInvoiceImmediately',
        'ErpPartialShipAllowed',
        'ErpTaxExempt',
        'CurrencyCode',
        'ErpLogicalId',
        'ErpAccountingEntityId',
        'ExchangeRate',
        'ErpSyncStatus',
        'AccountManager/*',
        'ErpLocation',
        'WarehouseLocation/*',
        'Location/*',
        'RequestedBy/NameLF',
        'Carrier/*',
      ],
    }];
  },
});

Manager.register(MODEL_NAMES.SALESORDER, MODEL_TYPES.SDATA, __class);
export default __class;
