define("Sage/UI/Controls/nls/zh-tw/PropertyStore", {
    // data types
    "文字": '文字',
    memo: '備忘',
    unicodeText: 'Unicode 文字',
    unicodeMemo: 'Unicode 備忘',
    "整數": '整數',
    "雙倍": '雙倍',
    single: '單一',
    "小數點": '小數點',
    "簡短": '簡短',
    standardId: '標準 ID',
    trueFalse: '真/假',
    yesNo: '是/否',
    "布林值": '布林值',
    dateTime: '日期/時間',
    email: '電子郵件',
    phone: '電話',
    pickList: '挑選清單',
    owner: '擁有者',
    lookup: '查閱',
    dependencyLookup: '相依性查閱',
    "圖表": '圖表',
    enum_: '列舉',
    "Guid": 'Guid',
    "位元組": '位元組',
    "二進位": '二進位',
    "URL": 'URL',
    "字串": '字串',
    "數字": '數字',
    id: 'ID',
    code: '代碼',
    name: '名稱',
    value: '值',
    "原生": '原生',
    calc: '計算欄位',
    calcSF: '計算字串',
    calcNF: '計算數字'

});
