define({
    lblNewEntityWizard: '新建实体向导',
    lblCreateEntity: 'Create Entity',
    lblCreateEntityFromTable: 'Create a new entity from a table',
    lblEntityName: '名称',
    lblDisplayName: '显示',
    lblPackage: '包',
    lblEntityUsed: 'Entity Name is already used !',
    lblNext: '下一步',
    lblCancel: '取消',
    lblBack: '返回',
    lblEnterProperties: 'Enter Fields',
    lblAddNewProperty: 'Click the add(+) button to add new fields to the entity',
    lblPropertyName: '字段名称',
    lblDataType: '数据类型',
    lblLength: '长度',
    lblSure: 'Are you sure ?',
    lblThisStepCreateEntity: '完成此步骤将创建实体以及必要的结构',
    lblEntity: '实体',
    lblProperties: '字段',
    lblStatus: '状态',
    lblSuccess: '成功',
    lblSuccessMsg: 'Success, Entity created Successfully.',
    lblError: '错误',
    lblFailed: 'Failed',
    lblErrorMsg: 'Error, Entity creation failed !',
    lblFinish: '完成',
    lblInvalidEntry: 'A valid entry starts with capital letter',
    lblRequired: '必需',
    lblErrorRelation: 'Error while creating relationship with',
    lblRelationship: '主要关系',
    lblSelectEntity: 'Choose whether this entity has a primary relationship to another entity',
    lblExistingEntity: '关联到现有实体',
    lblRelatedEntity: 'Related Entity',
    lblRelationType: 'Relation Type',
    addFieldDialogTitle: '添加字段',
    editFieldDialogTitle: '编辑字段',
    noDeleteSysProps: 'Can not delete the system properties',
    noEditSysProps: 'Can not edit the system properties',
    NoRecordsSelected: '未选择任何记录。',
    lblNullable: '可空',
    CreateUser: '创建用户',
    CreateDate: '创建日期',
    ModifyUser: '修改用户',
    ModifyDate: '修改日期'
});