define(
{
    txtGroup: '组',
    txtDateRange: '日期范围',
    txtUser: '用户',
    txtQuery: '查询',
    txtIsGreaterThan: '大于',
    txtIsLessThan: '小于',
    txtIsInTheRange: '在范围内',
    txtIsAfter: '之后',
    txtIsBefore: '之前',
    txtContains: '包含',
    txtStartsWith: '开始于',
    txtEndsWith: '结束于',
    txtIs: '是',
    txtIsNot: '不是',
    txtOnDemand: '根据需求',
    txtScheduled: '计划时间',
    txtCrystalReport: 'Crystal Report',
    txtExportToFileReportType: '导出到文件',
    txtUnknownReportType: '未知',
    txtNoFormat: '无格式',
    txtPdf: 'PDF',
    txtExcel: 'Excel',
    txtExcelDataOnly: 'Excel 数据',
    txtCsv: 'CSV',
    txtWord: 'Word',
    txtXml: 'XML'
});