define("Sage/UI/Controls/nls/de/FieldAttributeControlFactory", {
    IsEncrypted: 'Ist verschlüsselt',
    Length: 'Länge',
    Precision: 'Genauigkeit',
    Scale: 'Skalieren',
    LookupEntityName: 'Name der Suchentität',
    LookupGroup: 'Suchgruppe',
    IsPercentage: 'Prozentsatz?',
    Items: 'Einträge',
    MultiSelect: 'Mehrfachauswahl',
    OverriddenName: 'Überschriebener Name',
    Storage: 'Speicherung',
    EnableHyperLinking: 'Erstellung von Hyperlinks aktivieren',
    LookupPreFilters: 'Vorfilter für Suchen',
    EqualTo: 'Gleich',
    NotEqualTo: 'Nicht gleich',
    GreaterThanOrEqual: 'Größer gleich',
    GreaterThan: 'Größer als',
    LessThanOrEqual: 'Kleiner gleich',
    LessThan: 'Kleiner als',
    CondOperator: 'Bedingungsoperator',
    FilterValue: 'Filterwert',
    PropertyName: 'Name der Eigenschaft',
    LookupProperties: 'Sucheigenschaften',
    ExcludeFromFilters: 'Von Filtern ausschließen',
    HideCondition: 'Ausblende-Bedingung',
    IsSortable: 'Ist sortierbar',
    PropertyFormat: 'Eigenschaftsformat',
    None: 'Keine',
    Phone: 'Telefon',
    User: 'Benutzer',
    PickList: 'Auswahlliste',
    DateTime: 'Datum/Uhrzeit',
    PropertyFormatString: 'Eigenschaftsformatzeichenfolge',
    PropertyHeader: 'Eigenschaftsheader',
    PropertyType: 'Eigenschaftstyp',
    UseAsResult: 'Als Ergebnis verwenden',
    ReturnPrimaryKey: 'Primärschlüssel zurückgeben',
    AllowMultiples: 'Mehrfachauswahl zulassen',
    AlphaSort: 'Alphabetische Sortierung',
    MustExistInList: 'Muss in Liste enthalten sein',
    NoneEditable: 'Nichts bearbeitbar',
    PickListFilter: 'Auswahllistenfilter',
    ValueStoredAsText: 'Als Text gespeicherter Wert',
    Value: 'Wert',
    Display: 'Anzeigen',
    Code: 'Code',
    Name: 'Name',
    DisplayName: 'Anzeigename',
    Template: 'Formel',
    Description: 'Beschreibung',
    SortOrder: 'Sortierreihenfolge',
    lblNoFieldsInTemplate: 'Please add an entity property to the template before applying a sort order.',
    AddField: 'Feld hinzufügen',
    InUse: 'In Benutzung',
    NotInUse: 'Not In Use',
    CalculatedNumberInputError: "<p>Inputs are limited to Field Names selected via the drop down,<br/> and the following characters:<br/>&nbsp;&nbsp;&nbsp;&nbsp;'+','-','*','/','(', or ')',<br/>&nbsp;&nbsp;&nbsp;&nbsp;these match up with the button values above the text area.</p>",
    newPickList: 'Neue Auswahlliste',
    add: 'Hinzufügen',
    substract: 'substract',
    multiply: 'multiply',
    divide: 'divide',
    openParens: 'open parenthesis',
    closeParens: 'close parenthesis'
});
