define("Sage/MainView/EntityMgr/AddEditEntityDetail/nls/zh-cn/AddEditDialog", {
        // Add/Edit labels
        lblFilter: "筛选",
        lblMetric: "度量",
        lblFilters: "筛选器",
        lblMetrics: "度量",
        lblDistinct: "不相同",
        lblRange: "范围",
        lblUserLookup: "用户查找",
        lblAdd: "添加",
        lblEdit: "编辑",
        lblRemove: "移除",
        lblHelp: '帮助',
        lblFilterName: "筛选器名称",
        lblMetricName: "度量名称",
        lblDisplayName: "显示名称",
        lblName: "名称",
        lblDisplay: "显示",
        lblCalculated: "已计算",
        lblCalculation: "计算",
        lblDescription: "描述",
        lblFieldsName: "字段名称",
        lblCalculatedFieldsName: "已计算字段名称",
        lblFilterDp: "字段",
        lblTypeDp: "类型",
        lblCharacter: "字符",
        lblFrom: "从",
        lblTo: "至",
        lblOperators: "运算符",
        lblAggregation: "汇总",
        lblTypeSpecificContentBox: "特定于类型的内容框",
        lblSaveButton: "确定",
        lblCancelButton: "取消",
        DateDiffCheckerValue: "日期差异度量",
        InvalidFilterName: "筛选器名称无效",
        InvalidRangeName: "范围名称无效",
        RequiredFilterName: "必须提供筛选器名称",
        RequiredRangeName: "必须提供范围名称",
        FieldMustBeANumber: "字符字段必须是整数",
        SelectAnItem: "请选择项目",
        ItemRequired: "必需的项目",
        ItemInvalid: "项目无效",
        LowerMustBeLessThanUpper: "下限值必须小于上限值。",
        defaultRangeRowValue: "输入值",
        totalRecordCountLabel: "记录总数: ${0}",
        lblNew: "新建",
        lblExisting: "现有",
        lblExistingCalc: "现有已计算字段",
        validNameMsg: "有效条目以大写字母开头且 <br> 可以包含字母数字值和下划线。",
      
    propertyName: '名称',
    displayName: '显示',
    dataTypeId: '类型',
    dataTypeData: '类型属性',
    length: '长度',
    scale: '缩放',
    precision: '精度',
    isIncluded: '已包括',
    isReadOnly: '只读',
    displayCategory: '显示类别',
    sdata: 'Sdata',
    bulkAction: '批量操作',
    canBulkUpdate: '可批量更新',
    canImport: '导入',
    canMatch: '匹配',
    generate: '生成',
    audited: '已审计',
    //errors
    notUniqueFor: '对以下内容不唯一',
    notUnique: 'is not unique',
    nlsCode: 'NLS Code',
    nlsName: 'NLS Name',
    showTranslations: 'Show translations',
    hideTranslations: 'Hide translations',
    standardIds: '标准 ID',
    others: 'Others',
    SelectField: 'Please select a field !',
    SelectOneField: 'Please select only one field !',
    parent: 'Parent Entity and Join Field',
    child: 'Child Entity and Join Field',
    cardinality: '关系',
    cascade: '层叠',
    includeParent: 'Include parent relationship property in the child entity',
    includeChild: 'Include child relationship property in the parent entity',
    existingRelaton: 'This relationship already exists !'
   
});