define({
    lblNewEntityWizard: '新實體精靈',
    lblCreateEntity: 'Create Entity',
    lblCreateEntityFromTable: 'Create a new entity from a table',
    lblEntityName: '名稱',
    lblDisplayName: '顯示',
    lblPackage: '套件',
    lblEntityUsed: 'Entity Name is already used !',
    lblNext: '下一步',
    lblCancel: '取消',
    lblBack: '上一頁',
    lblEnterProperties: 'Enter Fields',
    lblAddNewProperty: 'Click the add(+) button to add new fields to the entity',
    lblPropertyName: '欄位名稱',
    lblDataType: '資料類型',
    lblLength: '長度',
    lblSure: 'Are you sure ?',
    lblThisStepCreateEntity: '完成這個步驟就會建立實體和必要的結構描述',
    lblEntity: '實體',
    lblProperties: '欄位',
    lblStatus: '狀態',
    lblSuccess: '成功',
    lblSuccessMsg: 'Success, Entity created Successfully.',
    lblError: '錯誤',
    lblFailed: 'Failed',
    lblErrorMsg: 'Error, Entity creation failed !',
    lblFinish: '完成',
    lblInvalidEntry: 'A valid entry starts with capital letter',
    lblRequired: '必要',
    lblErrorRelation: 'Error while creating relationship with',
    lblRelationship: '主要關聯',
    lblSelectEntity: 'Choose whether this entity has a primary relationship to another entity',
    lblExistingEntity: '與現有的實體相關',
    lblRelatedEntity: 'Related Entity',
    lblRelationType: 'Relation Type',
    addFieldDialogTitle: '新增欄位',
    editFieldDialogTitle: '編輯欄位',
    noDeleteSysProps: 'Can not delete the system properties',
    noEditSysProps: 'Can not edit the system properties',
    NoRecordsSelected: '未選取任何記錄。',
    lblNullable: '可為 Null',
    CreateUser: '建立使用者',
    CreateDate: '建立日期',
    ModifyUser: '修改使用者',
    ModifyDate: '修改日期'
});