define("Sage/Services/nls/zh-cn/ActivityService", (
{ txtErrorActionMsg: '很抱歉，操作已失败，发生了错误。',
  txtActivity: '活动',
  txtActivities: '活动',
  txtActionDeleteActivites: '删除活动',
  txtActionDeleteActivitiesQuestion: '将只删除您有权删除的活动。<P>是否确定要删除 {0} 个选中的“{1}”?',
  txtAlarm: '警报',
  txtAlarms: '警报',
  txtActionSnoozeAlarm: '推迟警报',
  txtActionSnoozeQuestion: '是否确定要针对“{2}”推迟 {0} 选中的“{1}”?',
  txtActionSnoozeAllQuestion: '是否确定要推迟“{1}”的所有“{0}”?',
  txtActionDismissAlarms: '消除警报',
  txtActionDismissAlarmsQuestion: '是否确定要消除 {0} 选中的“{1}”?',
  txtEvent: '事件',
  txtEvents: '事件',
  txtActionDeleteEvents: '删除事件',
  txtActionDeleteEventsQuestion: '将只删除您有权删除的事件。<P>是否确定要删除 {0} 个选中的“{1}”?',
  txtConfirmation: '确认',
  txtConfirmations: '确认',
  txtActionAcceptConfirmations: '接受确认',
  txtActionAcceptConfirmQuestion: '是否确定要接受 {0} 选中的“{1}”?仅对新建或更改的确认执行此操作。将忽略所有其他情况。',
  txtDeclineConfirmations: '拒绝确认',
  txtActionDeclineConfrimQuestion: '是否确定要拒绝 {0} 选中的“{1}”?仅对新建或更改的确认执行此操作。将忽略所有其他情况。',
  txtActionRemoveConfirmations: '删除确认',
  txtActionRemoveConfirmationsQuestion: '是否确定要删除 {0} 选中的“{1}”?仅对负责人、已拒绝或已删除的确认执行此操作。将忽略所有其他情况。',
  txtLiteratureRequest: '营销材料申请',
  txtLiteratureRequests: '营销材料申请',
  txtActionDeleteLiteratureRequests: '删除营销材料申请',
  txtActionDeleteLiteratureRequestsQuestion: '将只删除您有权删除的营销材料申请。<P>是否确定要删除 {0} 个选中的“{1}”?' }
));