define("Sage/UI/Controls/nls/zh-tw/FieldAttributeControlFactory", {
    IsEncrypted: '已加密',
    Length: '長度',
    Precision: '精確度',
    Scale: '縮放',
    LookupEntityName: '查閱實體名稱',
    LookupGroup: '查閱群組',
    IsPercentage: '為百分比',
    Items: '項目',
    MultiSelect: '複選',
    OverriddenName: '已覆寫名稱',
    Storage: '儲存空間',
    EnableHyperLinking: '啟用超連結',
    LookupPreFilters: '查閱預先篩選',
    EqualTo: '等於',
    NotEqualTo: '不等於',
    GreaterThanOrEqual: '大於或等於',
    GreaterThan: '大於',
    LessThanOrEqual: '小於或等於',
    LessThan: '小於',
    CondOperator: '條件運算子',
    FilterValue: '篩選值',
    PropertyName: '內容名稱',
    LookupProperties: '查閱內容',
    ExcludeFromFilters: '從篩選中排除',
    HideCondition: '隱藏條件',
    IsSortable: '可排序',
    PropertyFormat: '內容格式',
    None: '無',
    Phone: '電話',
    User: '使用者',
    PickList: '挑選清單',
    DateTime: '日期時間',
    PropertyFormatString: '內容格式字串',
    PropertyHeader: '內容標頭',
    PropertyType: '內容類型',
    UseAsResult: '做為結果',
    ReturnPrimaryKey: '傳回主索引鍵',
    AllowMultiples: '允許多個',
    AlphaSort: '依字母排序',
    MustExistInList: '必須在清單中',
    NoneEditable: '不可編輯',
    PickListFilter: '挑選清單篩選',
    ValueStoredAsText: '值已儲存為文字',
    Value: '值',
    Display: '顯示',
    Code: '代碼',
    Name: '名稱',
    DisplayName: '顯示名稱',
    Template: '計算',
    Description: '描述',
    SortOrder: '排序順序',
    lblNoFieldsInTemplate: 'Please add an entity property to the template before applying a sort order.',
    AddField: '新增欄位',
    InUse: '使用中',
    NotInUse: 'Not In Use',
    CalculatedNumberInputError: "<p>Inputs are limited to Field Names selected via the drop down,<br/> and the following characters:<br/>&nbsp;&nbsp;&nbsp;&nbsp;'+','-','*','/','(', or ')',<br/>&nbsp;&nbsp;&nbsp;&nbsp;these match up with the button values above the text area.</p>",
    newPickList: '新增挑選清單',
    add: '新增',
    substract: 'substract',
    multiply: 'multiply',
    divide: 'divide',
    openParens: 'open parenthesis',
    closeParens: 'close parenthesis'
});
