define("Sage/MainView/EntityMgr/AddEditEntityDetail/nls/de/AddEditDialog", {
        // Add/Edit labels
        lblFilter: "Filter",
        lblMetric: "Metrik",
        lblFilters: "Filter",
        lblMetrics: "Kennzahlen",
        lblDistinct: "Eindeutig",
        lblRange: "Bereich",
        lblUserLookup: "Benutzersuche",
        lblAdd: "Hinzufügen",
        lblEdit: "Bearbeiten",
        lblRemove: "Entfernen",
        lblHelp: 'Hilfe',
        lblFilterName: "Filtername",
        lblMetricName: "Kennzahlname",
        lblDisplayName: "Anzeigename",
        lblName: "Name",
        lblDisplay: "Anzeigen",
        lblCalculated: "Berechnet",
        lblCalculation: "Formel",
        lblDescription: "Beschreibung",
        lblFieldsName: "Feldername",
        lblCalculatedFieldsName: "Name berechneter Felder",
        lblFilterDp: "Felder",
        lblTypeDp: "Typ",
        lblCharacter: "Zeichen",
        lblFrom: "Von",
        lblTo: "An",
        lblOperators: "Operatoren",
        lblAggregation: "Aggregationen",
        lblTypeSpecificContentBox: "Typspezifischer Inhaltsbereich",
        lblSaveButton: "OK",
        lblCancelButton: "Abbrechen",
        DateDiffCheckerValue: "Kennzahl zum Datumsunterschied",
        InvalidFilterName: "Ungültiger Filtername",
        InvalidRangeName: "Ungültiger Bereichsname",
        RequiredFilterName: "Filtername ist erforderlich",
        RequiredRangeName: "Bereichsname ist erforderlich",
        FieldMustBeANumber: "Im Feld 'Zeichen' muss eine Ganzzahl eingegeben werden.",
        SelectAnItem: "Wählen Sie ein Element aus.",
        ItemRequired: "Element erforderlich",
        ItemInvalid: "Element ungültig",
        LowerMustBeLessThanUpper: "Unterer Wert muss kleiner sein als oberer Wert.",
        defaultRangeRowValue: "Wert eingeben",
        totalRecordCountLabel: "Gesamtzahl Datensätze: ${0}",
        lblNew: "Neu",
        lblExisting: "Vorhanden",
        lblExistingCalc: "Vorhandenes berechnetes Feld",
        validNameMsg: "Ein gültiger Eintrag beginnt mit einem Großbuchstaben und <br> kann alphanumerische Werte und Unterstriche enthalten.",
      
    propertyName: 'Name',
    displayName: 'Anzeigen',
    dataTypeId: 'Typ',
    dataTypeData: 'Typattribute',
    length: 'Länge',
    scale: 'Skalieren',
    precision: 'Genauigkeit',
    isIncluded: 'Enthalten',
    isReadOnly: 'Schreibgeschützt',
    displayCategory: 'Kategorie anzeigen',
    sdata: 'SData',
    bulkAction: 'Sammelaktion',
    canBulkUpdate: 'Massenaktualisierung möglich',
    canImport: 'Importieren',
    canMatch: 'Abgleichen',
    generate: 'Erstellen',
    audited: 'Geprüft',
    //errors
    notUniqueFor: 'ist nicht eindeutig für',
    notUnique: 'is not unique',
    nlsCode: 'NLS Code',
    nlsName: 'NLS Name',
    showTranslations: 'Show translations',
    hideTranslations: 'Hide translations',
    standardIds: 'Standard-IDs',
    others: 'Others',
    SelectField: 'Please select a field !',
    SelectOneField: 'Please select only one field !',
    parent: 'Parent Entity and Join Field',
    child: 'Child Entity and Join Field',
    cardinality: 'Beziehung',
    cascade: 'Kaskadieren',
    includeParent: 'Include parent relationship property in the child entity',
    includeChild: 'Include child relationship property in the parent entity',
    existingRelaton: 'This relationship already exists !'
   
});