define("Sage/UI/nls/zh-cn/NotesHistoryList", {
    typeText: '类型',
    showDbChangesText: '显示数据库变更',
    selectAllText: '全选',
    dateText: '日期',
    dateTimeText: '日期/时间',
    dateRangeText: '日期范围',
    userText: '用户',
    accountText: '客户',
    contactText: '联系人',
    opportunityText: '销售机会',
    regardingText: '事项',
    notesText: '备注',
    resultText: '结果',
    categoryText: '类别',
    sendEmailText: '通过电子邮件发送',
    sendToWordText: '发送到 Word',
    addNoteText: '添加备注',
    completeAnActivityText: '完成活动',
    helpText: '帮助',
    pleaseSelectRecordsText: '请选择一条或多条记录',
    UnableToFindWordMsg: '无法启动 Microsoft Word。请检查安全设置。',
    printedOnText: '打印时间'
});