define("Sage/UI/Controls/nls/fr/FieldAttributeControlFactory", {
    IsEncrypted: 'Est Crypté',
    Length: 'Longueur',
    Precision: 'Précision',
    Scale: 'Echelle',
    LookupEntityName: 'Recherche du nom de l\'entité',
    LookupGroup: 'Recherche du groupe',
    IsPercentage: 'Est un pourcentage ?',
    Items: 'Eléments',
    MultiSelect: 'Sélection multiple',
    OverriddenName: 'Nom remplacé',
    Storage: 'Stockage',
    EnableHyperLinking: 'Activer l\'hyperlien',
    LookupPreFilters: 'Rechercher dans les Pré-filtres',
    EqualTo: 'égal à',
    NotEqualTo: 'non égal à',
    GreaterThanOrEqual: 'Supérieur ou égal à',
    GreaterThan: 'Supérieur à',
    LessThanOrEqual: 'Inférieur ou égal à',
    LessThan: 'Inférieur à',
    CondOperator: 'Opérateur de condition',
    FilterValue: 'Valeur du filtre',
    PropertyName: 'Nom de propriété',
    LookupProperties: 'Propriétés de recherche',
    ExcludeFromFilters: 'Exclure des filtres',
    HideCondition: 'Masquer la condition',
    IsSortable: 'peut être trié',
    PropertyFormat: 'Format de propriété',
    None: 'Aucun',
    Phone: 'Téléphone',
    User: 'Utilisateur',
    PickList: 'Liste de sélection',
    DateTime: 'Date Heure',
    PropertyFormatString: 'Chaîne du format de propriété',
    PropertyHeader: 'En-tête de propriété',
    PropertyType: 'Type de propriété',
    UseAsResult: 'Utiliser comme résultat',
    ReturnPrimaryKey: 'Clé principale renvoyée',
    AllowMultiples: 'Autoriser des sélections multiples',
    AlphaSort: 'Trier par ordre alphabétique',
    MustExistInList: 'Doit exister dans la liste',
    NoneEditable: 'Aucun élément n\'est modifiable',
    PickListFilter: 'Filtre de liste déroulante',
    ValueStoredAsText: 'Valeur stockée comme texte',
    Value: 'Valeur',
    Display: 'Affichage',
    Code: 'Code',
    Name: 'Nom',
    DisplayName: 'Nom d\'affichage',
    Template: 'Calcul',
    Description: 'Description',
    SortOrder: 'Ordre de tri',
    lblNoFieldsInTemplate: 'Please add an entity property to the template before applying a sort order.',
    AddField: 'Ajouter un champ',
    InUse: 'En cours d\'utilisation',
    NotInUse: 'Not In Use',
    CalculatedNumberInputError: "<p>Inputs are limited to Field Names selected via the drop down,<br/> and the following characters:<br/>&nbsp;&nbsp;&nbsp;&nbsp;'+','-','*','/','(', or ')',<br/>&nbsp;&nbsp;&nbsp;&nbsp;these match up with the button values above the text area.</p>",
    newPickList: 'Nouvelle liste de sélection',
    add: 'Ajouter',
    substract: 'substract',
    multiply: 'multiply',
    divide: 'divide',
    openParens: 'open parenthesis',
    closeParens: 'close parenthesis'
});
