define("Sage/UI/Controls/nls/fr/PropertyStore", {
    // data types
    "Texte": 'Texte',
    memo: 'Mémo',
    unicodeText: 'Texte Unicode',
    unicodeMemo: 'Mémo Unicode',
    "Entier": 'Entier',
    "Double": 'Double',
    single: 'Unique',
    "Décimal": 'Décimal',
    "court": 'court',
    standardId: 'Id standard',
    trueFalse: 'Vrai / Faux',
    yesNo: 'Oui/Non',
    "Booléen": 'Booléen',
    dateTime: 'Date/Heure',
    email: 'E-mail',
    phone: 'Téléphone',
    pickList: 'Liste de sélection',
    owner: 'Propriétaire',
    lookup: 'Recherche',
    dependencyLookup: 'Recherche de dépendance',
    "Caractère": 'Caractère',
    enum_: 'Enum',
    "Guid": 'Guid',
    "Octet": 'Octet',
    "Binaire": 'Binaire',
    "Url": 'Url',
    "Chaîne": 'Chaîne',
    "Nombre": 'Nombre',
    id: 'ID',
    code: 'Code',
    name: 'Nom',
    value: 'Valeur',
    "Natif": 'Natif',
    calc: 'Champ calculé',
    calcSF: 'Chaîne calculée',
    calcNF: 'Nombre calculé'

});
