define("Sage/UI/Controls/nls/it/PropertyStore", {
    // data types
    "Testo": 'Testo',
    memo: 'Memo',
    unicodeText: 'testo unicode',
    unicodeMemo: 'memo unicode',
    "Intero": 'Intero',
    "doppio": 'doppio',
    single: 'Singolo',
    "Decimale": 'Decimale',
    "corto": 'corto',
    standardId: 'Id Standard',
    trueFalse: 'Vero/Falso',
    yesNo: 'Sì/No',
    "Booleano": 'Booleano',
    dateTime: 'Data/ora',
    email: 'E-Mail',
    phone: 'Telefono',
    pickList: 'Elenco di Selezione',
    owner: 'Proprietario',
    lookup: 'Ricerca',
    dependencyLookup: 'Ricerca dipendenze',
    "Carattere": 'Carattere',
    enum_: 'Enum',
    "guid": 'Guid',
    "byte": 'byte',
    "Binario": 'Binario',
    "Url": 'Url',
    "Stringa": 'Stringa',
    "Numero": 'Numero',
    id: 'Id',
    code: 'Codice',
    name: 'Nome',
    value: 'Valore',
    "Nativo": 'Nativo',
    calc: 'Campo calcolato',
    calcSF: 'Stringa calcolata',
    calcNF: 'Numero calcolato'

});
