define({
    addText: 'Hinzufügen',
    deleteText: 'Löschen',
    saveText: 'Speichern',
    cancelText: 'Abbrechen',
    editText: 'Bearbeiten',
    helpText: 'Hilfe',
    yesText: 'Ja',
    noText: 'Nein',
    okText: 'OK',
    newPickList: 'Neue Auswahlliste',
    items: 'Auswahllistenelemente',
    number: 'Reihenfolge',
    enterValue: 'Enter Value',
    lblMore: 'More',
    picklistAlreadyExists: "Picklist '${0}' already exists.",
    messageOnSave: 'Pick list, ${0}, has been saved. Please continue adding or editing the field information.',
    permissionsToView: 'You do not have permitions to view.',
    required: 'Erforderlicher Eintrag',
    allowMultiples: 'Mehrfachauswahl zulassen',
    valueMustExist: 'Text muss mit einem Listeneintrag übereinstimmen',
    alphaSorted: 'Alphabetisch sortiert',
    noneEditable: 'Users cannot edit items'
});