define("Sage/UI/Controls/nls/zh-cn/PropertyStore", {
    // data types
    "文本": '文本',
    memo: '备忘录',
    unicodeText: 'Unicode 文本',
    unicodeMemo: 'Unicode 备忘录',
    "整数": '整数',
    "双精度": '双精度',
    single: '单精度',
    "小数": '小数',
    "短": '短',
    standardId: '标准 ID',
    trueFalse: '真/假',
    yesNo: '是/否',
    "布尔值": '布尔值',
    dateTime: '日期/时间',
    email: '电子邮件',
    phone: '电话',
    pickList: '下拉列表',
    owner: '所有者',
    lookup: '查找',
    dependencyLookup: '依赖关系查找',
    "字符": '字符',
    enum_: '枚举',
    "Guid": 'Guid',
    "字节": '字节',
    "二进制": '二进制',
    "URL": 'URL',
    "字符串": '字符串',
    "数字": '数字',
    id: 'ID',
    code: '代码',
    name: '名称',
    value: '值',
    "本机": '本机',
    calc: '已计算字段',
    calcSF: '字符串计数',
    calcNF: '数字计数'

});
