define("Sage/MainView/EntityMgr/AddEditEntityDetail/nls/ru/AddEditDialog", {
        // Add/Edit labels
        lblFilter: "Фильтр",
        lblMetric: "Метрика",
        lblFilters: "Фильтры",
        lblMetrics: "Метрики",
        lblDistinct: "Уникальный",
        lblRange: "Диапазон",
        lblUserLookup: "Поиск пользователя",
        lblAdd: "Добавить",
        lblEdit: "Изменить",
        lblRemove: "Исключить",
        lblHelp: 'Помощь',
        lblFilterName: "Название фильтра",
        lblMetricName: "Название метрики",
        lblDisplayName: "Название",
        lblName: "Имя",
        lblDisplay: "Отображение",
        lblCalculated: "Рассчитано",
        lblCalculation: "Вычисление",
        lblDescription: "Описание",
        lblFieldsName: "Имя поля",
        lblCalculatedFieldsName: "Имя вычисляемого поля",
        lblFilterDp: "Поля",
        lblTypeDp: "Тип",
        lblCharacter: "Символ",
        lblFrom: "От",
        lblTo: "Кому",
        lblOperators: "Операторы",
        lblAggregation: "Агрегации",
        lblTypeSpecificContentBox: "Поле данных, уникальных для типа",
        lblSaveButton: "ОК",
        lblCancelButton: "Отмена",
        DateDiffCheckerValue: "Промежуток между датами",
        InvalidFilterName: "Неправильное название фильтра",
        InvalidRangeName: "Неверное имя диапазона",
        RequiredFilterName: "Требуется имя фильтра",
        RequiredRangeName: "Требуется имя диапазона",
        FieldMustBeANumber: "Поле символа должно иметь целочисленное значение",
        SelectAnItem: "Выберите элемент",
        ItemRequired: "Требуется элемент",
        ItemInvalid: "Неверный элемент",
        LowerMustBeLessThanUpper: "Нижнее значение должно быть меньше верхнего значения.",
        defaultRangeRowValue: "Введите значение",
        totalRecordCountLabel: "Всего записей: ${0}",
        lblNew: "Создать",
        lblExisting: "Существующий",
        lblExistingCalc: "Сущ. вычисляемое поле",
        validNameMsg: "Допустимая запись должна начинаться с заглавной буквы и <br> может содержать буквы, цифры и символы подчеркивания.",
      
    propertyName: 'Имя',
    displayName: 'Отображение',
    dataTypeId: 'Тип',
    dataTypeData: 'Атрибуты типа',
    length: 'Длина',
    scale: 'Шкала',
    precision: 'Точность',
    isIncluded: 'Включено',
    isReadOnly: 'Только для чтения',
    displayCategory: 'Показать категорию',
    sdata: 'SData',
    bulkAction: 'Массовое действие',
    canBulkUpdate: 'Разрешено массовое обновление',
    canImport: 'Импорт',
    canMatch: 'Выполняются',
    generate: 'Создать',
    audited: 'Проверка',
    //errors
    notUniqueFor: 'не уникально для',
    notUnique: 'is not unique',
    nlsCode: 'NLS Code',
    nlsName: 'NLS Name',
    showTranslations: 'Show translations',
    hideTranslations: 'Hide translations',
    standardIds: 'Стандартные ИД',
    others: 'Others',
    SelectField: 'Please select a field !',
    SelectOneField: 'Please select only one field !',
    parent: 'Parent Entity and Join Field',
    child: 'Child Entity and Join Field',
    cardinality: 'Связь',
    cascade: 'Каскадом',
    includeParent: 'Include parent relationship property in the child entity',
    includeChild: 'Include child relationship property in the parent entity',
    existingRelaton: 'This relationship already exists !'
   
});