define("Sage/UI/Controls/nls/zh-cn/FieldAttributeControlFactory", {
    IsEncrypted: '是否加密',
    Length: '长度',
    Precision: '精度',
    Scale: '缩放',
    LookupEntityName: '查找实体名称',
    LookupGroup: '查找组',
    IsPercentage: '百分比',
    Items: '项目',
    MultiSelect: '多选',
    OverriddenName: '覆盖的名称',
    Storage: '存储器',
    EnableHyperLinking: '启用超链接',
    LookupPreFilters: '查找预筛选器',
    EqualTo: '等于',
    NotEqualTo: '不等于',
    GreaterThanOrEqual: '大于等于',
    GreaterThan: '大于',
    LessThanOrEqual: '小于等于',
    LessThan: '小于',
    CondOperator: '条件运算符',
    FilterValue: '筛选器值',
    PropertyName: '属性名称',
    LookupProperties: '查找属性',
    ExcludeFromFilters: '从筛选器中排除',
    HideCondition: '隐藏条件',
    IsSortable: '可排序',
    PropertyFormat: '属性格式',
    None: '无',
    Phone: '电话',
    User: '用户',
    PickList: '下拉列表',
    DateTime: '日期时间',
    PropertyFormatString: '属性格式字符串',
    PropertyHeader: '属性标题',
    PropertyType: '属性类型',
    UseAsResult: '用作结果',
    ReturnPrimaryKey: '返回主键',
    AllowMultiples: '允许多个值',
    AlphaSort: 'Alpha 排序',
    MustExistInList: '必须存在于列表中',
    NoneEditable: '不可编辑',
    PickListFilter: '下拉列表筛选器',
    ValueStoredAsText: '值存储为文本',
    Value: '值',
    Display: '显示',
    Code: '代码',
    Name: '名称',
    DisplayName: '显示名称',
    Template: '计算',
    Description: '描述',
    SortOrder: '排序顺序',
    lblNoFieldsInTemplate: 'Please add an entity property to the template before applying a sort order.',
    AddField: '添加字段',
    InUse: '使用中',
    NotInUse: 'Not In Use',
    CalculatedNumberInputError: "<p>Inputs are limited to Field Names selected via the drop down,<br/> and the following characters:<br/>&nbsp;&nbsp;&nbsp;&nbsp;'+','-','*','/','(', or ')',<br/>&nbsp;&nbsp;&nbsp;&nbsp;these match up with the button values above the text area.</p>",
    newPickList: '新建下拉列表',
    add: '添加',
    substract: 'substract',
    multiply: 'multiply',
    divide: 'divide',
    openParens: 'open parenthesis',
    closeParens: 'close parenthesis'
});
