define((
{ titleScheduleText: '排程事件',
  titleEditText: '編輯事件',
  lblDayTypeText: '日類型:',
  lblStartDateText: '開始日期:',
  lblEndDateText: '結束日期:',
  lblUserText: '使用者:',
  lookupUserText: '查閱使用者',
  lblCategoryText: '類別:',
  lblLocationText: '地點:',
  lblDescriptionText: '描述:',
  btnOkayText: '確定',
  btnCancelText: '取消',
  btnHelpText: '說明',
  eventTypeActiveText: '作用中',
  eventTypeBusinessTripText: '出差',
  eventTypeConferenceText: '會議',
  eventTypeHolidayText: '假日',
  eventTypeOffText: '請假',
  eventTypeTradeShowText: '商展',
  eventTypeUnavailableText: '忙碌',
  eventTypeVacationText: '休假',
  errorText: '很抱歉，無法建立事件，因為發生錯誤。',
  invaildDatesText: '抱歉，結束日期不能早於開始日期。',
  nameText: '名稱' }
));